import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../globals.css";
import Header from "./_components/header";
import Sidebar from "./_components/sidebar";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const {session} = await getUser()

    if (!session) {
      return redirect('/dashboard/sign-in')
    }

  return (
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <Header />
            <main className="p-4">{children}</main>
          </div>
        </div>
  );
}
